'use client'

import { motion } from 'framer-motion'
import { ExternalLink, Github, ArrowUpRight, Lock, Sparkles } from 'lucide-react'
import Badge from '@/components/ui/Badge'
import { cn } from '@/lib/utils'
import { useAchievementTracker } from '@/lib/easter-eggs'

interface SecretProject {
  id: string
  name: string
  emoji: string
  tagline: string
  description: string
  category: string
  technologies: string[]
  liveUrl?: string
  githubUrl?: string
  requiredAchievement: string
  funFact?: string
}

const SECRET_PROJECTS: SecretProject[] = [
  {
    id: 'time-waster-3000',
    name: 'Time Waster 3000',
    emoji: '⏰',
    tagline: 'ULTIMATE PROCRASTINATION TOOL',
    description: 'A revolutionary app that helps you waste time efficiently. Features include: staring contest simulator, loading bar watcher, and infinite scroll generator.',
    category: 'entertainment',
    technologies: ['Procrastination.js', 'TimeTheft', 'ScrollForever', 'NoProductivity'],
    requiredAchievement: 'konami-master',
    funFact: '127% of users reported getting nothing done after using this app.',
  },
  {
    id: 'bug-generator',
    name: 'Bug Generator Pro',
    emoji: '🐛',
    tagline: 'CREATES BUGS AUTOMATICALLY',
    description: 'Tired of writing bug-free code? This tool automatically introduces subtle bugs into your codebase. Premium features include off-by-one errors and race conditions.',
    category: 'tools',
    technologies: ['Chaos.js', 'RandomError', 'MurphyLaw', 'Undefined'],
    githubUrl: 'https://github.com/null/void',
    requiredAchievement: 'dev-console-found',
    funFact: 'Originally built for April Fools, but developers found it too realistic.',
  },
  {
    id: 'coffee-tracker',
    name: 'Coffee Overflow',
    emoji: '☕',
    tagline: 'CAFFEINE DEPENDENCY MANAGER',
    description: 'Track your coffee consumption and get reminded when your blood-to-caffeine ratio drops below critical levels. Includes emergency coffee location finder.',
    category: 'productivity',
    technologies: ['CaffeineAPI', 'ShakingHands.css', 'SleepDeprivation', 'JavaBean'],
    liveUrl: 'https://definitely-not-coffee-addiction.com',
    requiredAchievement: 'easter-egg-hunter',
    funFact: 'The debug console outputs "undefined" in Comic Sans when you\'re over-caffeinated.',
  },
  {
    id: 'semicolon-finder',
    name: 'Semicolon Finder',
    emoji: ';',
    tagline: 'NEVER LOSE A SEMICOLON AGAIN',
    description: 'Advanced AI-powered tool that locates missing semicolons in your code. Also finds unnecessary ones and judges you for them.',
    category: 'tools',
    technologies: ['Python', 'JavaScript', 'Irony.js', 'PunctuationML'],
    requiredAchievement: 'secret-unlocker',
    funFact: 'Written entirely in Python (which doesn\'t need semicolons).',
  },
  {
    id: 'readme-excuses',
    name: 'README.md Generator',
    emoji: '📝',
    tagline: 'DOCUMENTATION PROCRASTINATOR',
    description: 'Automatically generates impressive-sounding README files for projects with no documentation. Features: TODO list filler, "coming soon" promise maker, badge inflator.',
    category: 'tools',
    technologies: ['MarkdownMagic', 'EmptyPromises', 'BadgeCollector', 'VaporAPI'],
    githubUrl: 'https://github.com/coming/soon',
    requiredAchievement: 'cursor-explorer',
    funFact: 'The README for this project was generated by itself (recursively, forever).',
  },
  {
    id: 'ai-excuse-generator',
    name: 'AI Excuse Generator',
    emoji: '🤖',
    tagline: 'BLAME IT ON THE AI',
    description: 'Generate believable excuses for why your code doesn\'t work. Powered by ChatGPT-None. "It worked in production" and "Must be a browser issue" templates included.',
    category: 'ai',
    technologies: ['GPT-NOPE', 'ExcuseML', 'BlameBot', 'NotMyFault.js'],
    liveUrl: 'https://its-not-a-bug-its-a-feature.ai',
    requiredAchievement: 'speed-runner',
    funFact: 'When asked to fix itself, it blamed the user.',
  },
  {
    id: 'dark-mode-darker',
    name: 'Dark Mode: Darker',
    emoji: '🌚',
    tagline: 'WHEN DARK MODE ISN\'T DARK ENOUGH',
    description: 'A theme so dark, it absorbs light from your monitor. Warning: May cause existential dread. Includes ultra-dark, void-black, and "did my screen turn off?" modes.',
    category: 'tools',
    technologies: ['VoidCSS', 'rgb(0,0,0)', 'BlackHole.theme', 'NoLight'],
    requiredAchievement: 'night-owl',
    funFact: 'The light mode version is just a black screen with white text.',
  },
  {
    id: 'console-log-beautifier',
    name: 'console.log() Beautifier',
    emoji: '🎨',
    tagline: 'MAKES YOUR DEBUGGING PRETTY',
    description: 'Transforms boring console logs into beautiful rainbow unicorn emojis. Because if you\'re going to debug, do it with style. Includes ASCII art errors.',
    category: 'tools',
    technologies: ['RainbowLog', 'EmojiDebug', 'UnicornJS', 'PrettyErrors'],
    requiredAchievement: 'vault-explorer',
    funFact: 'Increases debugging time by 300%, but makes you feel better about it.',
  },
]

interface SecretProjectCardProps {
  project: SecretProject
  index?: number
  isLocked?: boolean
}

export function SecretProjectCard({
  project,
  index = 0,
  isLocked = false,
}: SecretProjectCardProps) {
  if (isLocked) {
    return (
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        whileInView={{ opacity: 1, y: 0 }}
        viewport={{ once: true }}
        transition={{ duration: 0.5, delay: index * 0.1 }}
        className="group relative rounded-xl border-2 border-dashed border-muted-foreground/30 bg-muted/20 overflow-hidden"
      >
        <div className="p-6 flex flex-col items-center justify-center min-h-[300px] text-center">
          <motion.div
            animate={{ rotate: [0, -5, 5, 0] }}
            transition={{ duration: 2, repeat: Infinity, repeatDelay: 1 }}
          >
            <Lock className="w-12 h-12 text-muted-foreground mb-4" />
          </motion.div>
          <h3 className="font-bold text-lg mb-2 text-muted-foreground">
            Secret Project Locked
          </h3>
          <p className="text-sm text-muted-foreground/70 mb-4">
            Discover achievements to unlock hidden projects
          </p>
          <Badge variant="outline" size="sm">
            Achievement Required
          </Badge>
        </div>
      </motion.div>
    )
  }

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true }}
      transition={{ duration: 0.5, delay: index * 0.1 }}
      className={cn(
        'group relative rounded-xl border-2 border-purple-500/50 bg-gradient-to-br from-purple-500/10 via-pink-500/10 to-orange-500/10 overflow-hidden',
        'hover:border-purple-500 transition-all duration-300 hover:shadow-lg hover:shadow-purple-500/20'
      )}
    >
      <div className="absolute top-3 right-3 z-10">
        <Badge
          variant="default"
          size="sm"
          className="bg-purple-500 text-white border-none"
        >
          <Sparkles className="w-3 h-3 mr-1" />
          Secret
        </Badge>
      </div>

      <div className="p-6">
        <div className="flex items-start justify-between mb-4">
          <div className="flex items-center gap-3">
            <motion.span
              className="text-3xl"
              animate={{ rotate: [0, 10, -10, 0] }}
              transition={{ duration: 2, repeat: Infinity, repeatDelay: 3 }}
            >
              {project.emoji}
            </motion.span>
            <div>
              <h3 className="font-bold text-lg group-hover:text-purple-500 transition-colors">
                {project.name}
              </h3>
              <span className="text-xs text-muted-foreground uppercase tracking-wider">
                {project.tagline}
              </span>
            </div>
          </div>
        </div>

        <p className="text-muted-foreground mb-4 text-sm leading-relaxed">
          {project.description}
        </p>

        {project.funFact && (
          <div className="mb-4 p-3 bg-muted/50 rounded-lg border border-border">
            <p className="text-xs text-muted-foreground">
              <span className="font-semibold">Fun Fact:</span> {project.funFact}
            </p>
          </div>
        )}

        <div className="flex flex-wrap gap-2 mb-4">
          {project.technologies.map((tech) => (
            <Badge key={tech} variant="secondary" size="sm">
              {tech}
            </Badge>
          ))}
        </div>

        <div className="flex items-center gap-3 pt-4 border-t border-border/50">
          {project.liveUrl ? (
            <a
              href={project.liveUrl}
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-2 text-sm font-medium hover:text-purple-500 transition-colors"
              onClick={(e) => {
                e.preventDefault()
                alert('Just kidding! This is a joke project 😄')
              }}
            >
              <ExternalLink className="w-4 h-4" />
              Live Demo
            </a>
          ) : (
            <span className="inline-flex items-center gap-2 text-sm font-medium text-muted-foreground/50">
              <ExternalLink className="w-4 h-4" />
              No Demo
            </span>
          )}
          {project.githubUrl && (
            <a
              href={project.githubUrl}
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-2 text-sm font-medium text-muted-foreground hover:text-foreground transition-colors"
              onClick={(e) => {
                e.preventDefault()
                alert('Error 404: Humor not found 🤷')
              }}
            >
              <Github className="w-4 h-4" />
              Source
            </a>
          )}
        </div>
      </div>

      <motion.div
        initial={{ opacity: 0, x: -10 }}
        whileHover={{ opacity: 1, x: 0 }}
        className="absolute top-4 right-4 opacity-0 group-hover:opacity-100 transition-opacity"
      >
        <ArrowUpRight className="w-5 h-5 text-purple-500" />
      </motion.div>

      <div className="absolute inset-0 bg-gradient-to-br from-purple-500/5 to-pink-500/5 opacity-0 group-hover:opacity-100 transition-opacity pointer-events-none" />
    </motion.div>
  )
}

export default function SecretProjectsList() {
  const { hasAchievement } = useAchievementTracker()

  const unlockedProjects = SECRET_PROJECTS.filter((project) =>
    hasAchievement(project.requiredAchievement)
  )

  const hasAnySecretProjects = unlockedProjects.length > 0

  const lockedCount = SECRET_PROJECTS.length - unlockedProjects.length

  if (!hasAnySecretProjects) {
    return null
  }

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true }}
      transition={{ duration: 0.5 }}
      className="mt-16 pt-16 border-t-2 border-dashed border-purple-500/30"
    >
      <div className="text-center mb-8">
        <motion.div
          animate={{ rotate: [0, 360] }}
          transition={{ duration: 20, repeat: Infinity, ease: 'linear' }}
          className="inline-block mb-4"
        >
          <Sparkles className="w-8 h-8 text-purple-500" />
        </motion.div>
        <h2 className="text-3xl md:text-4xl font-bold mb-4 bg-gradient-to-r from-purple-500 via-pink-500 to-orange-500 bg-clip-text text-transparent">
          Secret Projects Unlocked
        </h2>
        <p className="text-muted-foreground max-w-2xl mx-auto text-lg mb-4">
          You've discovered {unlockedProjects.length} of {SECRET_PROJECTS.length} hidden joke projects! 
          These don't actually exist... or do they? 🤔
        </p>
        {lockedCount > 0 && (
          <Badge variant="outline" size="md" className="border-purple-500/50">
            {lockedCount} more secret{lockedCount !== 1 ? 's' : ''} to unlock
          </Badge>
        )}
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {unlockedProjects.map((project, index) => (
          <SecretProjectCard
            key={project.id}
            project={project}
            index={index}
            isLocked={false}
          />
        ))}
        {lockedCount > 0 &&
          Array.from({ length: Math.min(2, lockedCount) }).map((_, index) => (
            <SecretProjectCard
              key={`locked-${index}`}
              project={{} as SecretProject}
              index={unlockedProjects.length + index}
              isLocked={true}
            />
          ))}
      </div>
    </motion.div>
  )
}
